
package fr.s2re.stock.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IStockWebService", targetNamespace = "http://webservice.stock.s2re.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IStockWebService {


    /**
     * 
     * @param paramProduit
     * @return
     *     returns fr.s2re.stock.webservice.ProduitDto
     */
    @WebMethod
    @WebResult(name = "produitUpdate", targetNamespace = "")
    @RequestWrapper(localName = "updateProduit", targetNamespace = "http://webservice.stock.s2re.fr", className = "fr.s2re.stock.webservice.UpdateProduit")
    @ResponseWrapper(localName = "updateProduitResponse", targetNamespace = "http://webservice.stock.s2re.fr", className = "fr.s2re.stock.webservice.UpdateProduitResponse")
    public ProduitDto updateProduit(
        @WebParam(name = "paramProduit", targetNamespace = "")
        ProduitDto paramProduit);

    /**
     * 
     * @param paramReference
     * @return
     *     returns fr.s2re.stock.webservice.ProduitDto
     */
    @WebMethod
    @WebResult(name = "produitByReference", targetNamespace = "")
    @RequestWrapper(localName = "getProduitByReference", targetNamespace = "http://webservice.stock.s2re.fr", className = "fr.s2re.stock.webservice.GetProduitByReference")
    @ResponseWrapper(localName = "getProduitByReferenceResponse", targetNamespace = "http://webservice.stock.s2re.fr", className = "fr.s2re.stock.webservice.GetProduitByReferenceResponse")
    public ProduitDto getProduitByReference(
        @WebParam(name = "paramReference", targetNamespace = "")
        String paramReference);

}
