
package fr.s2re.stock.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "webServiceStock", targetNamespace = "http://webservice.stock.s2re.fr", wsdlLocation = "http://localhost:28080/Stock/services/springServiceStock?wsdl")
public class WebServiceStock
    extends Service
{

    private final static URL WEBSERVICESTOCK_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICESTOCK_EXCEPTION;
    private final static QName WEBSERVICESTOCK_QNAME = new QName("http://webservice.stock.s2re.fr", "webServiceStock");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:28080/Stock/services/springServiceStock?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICESTOCK_WSDL_LOCATION = url;
        WEBSERVICESTOCK_EXCEPTION = e;
    }

    public WebServiceStock() {
        super(__getWsdlLocation(), WEBSERVICESTOCK_QNAME);
    }

    public WebServiceStock(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICESTOCK_QNAME, features);
    }

    public WebServiceStock(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICESTOCK_QNAME);
    }

    public WebServiceStock(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICESTOCK_QNAME, features);
    }

    public WebServiceStock(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceStock(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IStockWebService
     */
    @WebEndpoint(name = "StockWebServiceImplPort")
    public IStockWebService getStockWebServiceImplPort() {
        return super.getPort(new QName("http://webservice.stock.s2re.fr", "StockWebServiceImplPort"), IStockWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IStockWebService
     */
    @WebEndpoint(name = "StockWebServiceImplPort")
    public IStockWebService getStockWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.stock.s2re.fr", "StockWebServiceImplPort"), IStockWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICESTOCK_EXCEPTION!= null) {
            throw WEBSERVICESTOCK_EXCEPTION;
        }
        return WEBSERVICESTOCK_WSDL_LOCATION;
    }

}
