
package fr.s2re.banque.servicebanque;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServiceBanqueWebService", targetNamespace = "http://servicebanque.banque.s2re.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IServiceBanqueWebService {


    /**
     * 
     * @param paramcarteBancairee
     * @param paramNomClient
     * @param paramMontantCommande
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifierSolde", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.VerifierSolde")
    @ResponseWrapper(localName = "verifierSoldeResponse", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.VerifierSoldeResponse")
    public boolean verifierSolde(
        @WebParam(name = "paramNomClient", targetNamespace = "")
        String paramNomClient,
        @WebParam(name = "paramMontantCommande", targetNamespace = "")
        double paramMontantCommande,
        @WebParam(name = "paramcarteBancairee", targetNamespace = "")
        CarteBancaireDto paramcarteBancairee);

    /**
     * 
     * @param montant
     * @param typeOperation
     * @param idOperation
     * @param dateOperation
     * @param comptebancaire
     * @return
     *     returns fr.s2re.banque.servicebanque.OperationBancaireDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertDebit", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.InsertDebit")
    @ResponseWrapper(localName = "insertDebitResponse", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.InsertDebitResponse")
    public OperationBancaireDto insertDebit(
        @WebParam(name = "idOperation", targetNamespace = "")
        int idOperation,
        @WebParam(name = "dateOperation", targetNamespace = "")
        XMLGregorianCalendar dateOperation,
        @WebParam(name = "montant", targetNamespace = "")
        double montant,
        @WebParam(name = "typeOperation", targetNamespace = "")
        String typeOperation,
        @WebParam(name = "comptebancaire", targetNamespace = "")
        CompteBancaireDto comptebancaire);

    /**
     * 
     * @param paramidClient
     * @return
     *     returns java.util.List<fr.s2re.banque.servicebanque.CarteBancaireDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCarteByClient", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.GetCarteByClient")
    @ResponseWrapper(localName = "getCarteByClientResponse", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.GetCarteByClientResponse")
    public List<CarteBancaireDto> getCarteByClient(
        @WebParam(name = "paramidClient", targetNamespace = "")
        Integer paramidClient);

    /**
     * 
     * @param montant
     * @param typeOperation
     * @param idOperation
     * @param dateOperation
     * @param comptebancaire
     * @return
     *     returns fr.s2re.banque.servicebanque.OperationBancaireDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertCredit", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.InsertCredit")
    @ResponseWrapper(localName = "insertCreditResponse", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.InsertCreditResponse")
    public OperationBancaireDto insertCredit(
        @WebParam(name = "idOperation", targetNamespace = "")
        int idOperation,
        @WebParam(name = "dateOperation", targetNamespace = "")
        XMLGregorianCalendar dateOperation,
        @WebParam(name = "montant", targetNamespace = "")
        double montant,
        @WebParam(name = "typeOperation", targetNamespace = "")
        String typeOperation,
        @WebParam(name = "comptebancaire", targetNamespace = "")
        CompteBancaireDto comptebancaire);

    /**
     * 
     * @param paramNom
     * @return
     *     returns fr.s2re.banque.servicebanque.ClientDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCLientByNom", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.GetCLientByNom")
    @ResponseWrapper(localName = "getCLientByNomResponse", targetNamespace = "http://servicebanque.banque.s2re.fr", className = "fr.s2re.banque.servicebanque.GetCLientByNomResponse")
    public ClientDto getCLientByNom(
        @WebParam(name = "paramNom", targetNamespace = "")
        String paramNom);

}
