
package fr.s2re.livraison.servicelivraison;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceLivraisonWS", targetNamespace = "http://servicelivraison.livraison.s2re.fr", wsdlLocation = "http://localhost:18080/LivraisonWebService/ServiceLivraisonWS/ServiceLivraisonWebServiceImpl?wsdl")
public class ServiceLivraisonWS
    extends Service
{

    private final static URL SERVICELIVRAISONWS_WSDL_LOCATION;
    private final static WebServiceException SERVICELIVRAISONWS_EXCEPTION;
    private final static QName SERVICELIVRAISONWS_QNAME = new QName("http://servicelivraison.livraison.s2re.fr", "ServiceLivraisonWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18080/LivraisonWebService/ServiceLivraisonWS/ServiceLivraisonWebServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICELIVRAISONWS_WSDL_LOCATION = url;
        SERVICELIVRAISONWS_EXCEPTION = e;
    }

    public ServiceLivraisonWS() {
        super(__getWsdlLocation(), SERVICELIVRAISONWS_QNAME);
    }

    public ServiceLivraisonWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICELIVRAISONWS_QNAME, features);
    }

    public ServiceLivraisonWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICELIVRAISONWS_QNAME);
    }

    public ServiceLivraisonWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICELIVRAISONWS_QNAME, features);
    }

    public ServiceLivraisonWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceLivraisonWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ILivraisonWebService
     */
    @WebEndpoint(name = "ServiceLivraisonWebServiceImplPort")
    public ILivraisonWebService getServiceLivraisonWebServiceImplPort() {
        return super.getPort(new QName("http://servicelivraison.livraison.s2re.fr", "ServiceLivraisonWebServiceImplPort"), ILivraisonWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ILivraisonWebService
     */
    @WebEndpoint(name = "ServiceLivraisonWebServiceImplPort")
    public ILivraisonWebService getServiceLivraisonWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicelivraison.livraison.s2re.fr", "ServiceLivraisonWebServiceImplPort"), ILivraisonWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICELIVRAISONWS_EXCEPTION!= null) {
            throw SERVICELIVRAISONWS_EXCEPTION;
        }
        return SERVICELIVRAISONWS_WSDL_LOCATION;
    }

}
