
package fr.s2re.bpel.stock;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StockBPEL", targetNamespace = "http://stock.bpel.s2re.fr", wsdlLocation = "http://localhost:8080/ode/processes/StockBPEL?wsdl")
public class StockBPEL
    extends Service
{

    private final static URL STOCKBPEL_WSDL_LOCATION;
    private final static WebServiceException STOCKBPEL_EXCEPTION;
    private final static QName STOCKBPEL_QNAME = new QName("http://stock.bpel.s2re.fr", "StockBPEL");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ode/processes/StockBPEL?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STOCKBPEL_WSDL_LOCATION = url;
        STOCKBPEL_EXCEPTION = e;
    }

    public StockBPEL() {
        super(__getWsdlLocation(), STOCKBPEL_QNAME);
    }

    public StockBPEL(WebServiceFeature... features) {
        super(__getWsdlLocation(), STOCKBPEL_QNAME, features);
    }

    public StockBPEL(URL wsdlLocation) {
        super(wsdlLocation, STOCKBPEL_QNAME);
    }

    public StockBPEL(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STOCKBPEL_QNAME, features);
    }

    public StockBPEL(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StockBPEL(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StockBPELPortType
     */
    @WebEndpoint(name = "StockBPELPort")
    public StockBPELPortType getStockBPELPort() {
        return super.getPort(new QName("http://stock.bpel.s2re.fr", "StockBPELPort"), StockBPELPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockBPELPortType
     */
    @WebEndpoint(name = "StockBPELPort")
    public StockBPELPortType getStockBPELPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://stock.bpel.s2re.fr", "StockBPELPort"), StockBPELPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STOCKBPEL_EXCEPTION!= null) {
            throw STOCKBPEL_EXCEPTION;
        }
        return STOCKBPEL_WSDL_LOCATION;
    }

}
